# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Random notes
email: maltsevm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://miyuki-chan.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  miyuki-chan
exclude:
    - temp

# Build settings
markdown: kramdown
theme: minima
